export const GATEWAY_URL = "http://localhost:3006"
export const ACCESS_EP = "/token"
export const USERS_EP = "/users/"
export const BLOCK_USER_EP = "/users/blocked/"
export const UNBLOCK_USER_EP = "/users/unblocked/"
export const METRICS_BLOCKED_EP = "/metrics/blocked_users/"
export const METRICS_LOGINS_EP = "/metrics/logins"
export const METRICS_REGISTRATIONS_EP = "/metrics/registrations"
export const PRICING_EP = "/pricing/"
export const PRICING_MOD_EP = "/pricing/cost/"

export const PAGE_UNAVAILABLE_MSG = "Content unavailable"