export const GATEWAY_URL = "http://localhost:3007"
export const ACCESS_EP = "/admins/grantaccess"
export const USERS_EP = "/users/"
export const BLOCK_USER_EP = "/users/blocked/"
export const UNBLOCK_USER_EP = "/users/unblocked/"